### PR TITLE
 update to patient queue

### PR DESCRIPTION
**Pull request by waleplanet**
Fixes #[replace brackets with the issue number that your pull request addresses].

**Changes proposed in this pull request:**
- [list out summary of changes here]
- [list out summary of changes here]
- [list out summary of changes here]
- [etc]

*Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Thanks! (you can delete this text)*

cc @HospitalRun/core-maintainers

### CODE REVIEW

**Comment by waleplanet** [comment]
screenshot from 2017-07-26 16-10-59
screenshot from 2017-07-26 16-11-13

**Comment by noxecane** [comment]
So first of all there is a described workflow of how dariya in its simplest form is supposed to operate. Just recap:

1. Patient goes to OPD(Outpatient Department) to ask to see the doctor.

2. OPD confirms that patient is registered by searching for patient, and if patient is not registers the patient.

3. OPD then schedules an appointment for the patient. 

4. At the nursing station the nurse checks for the next patient on the queue and the records the vitals into a limit aware vitals editor and then removes the patient from his/her queue

5. At the doctors office he fills out the patient's complaints, his observations, diagnosis, planned procedures and prescriptions.

So the question is how your patch can help if not purely replicate but facilitate this kind of process.

**Comment by waleplanet** [comment]
How I designed this to work from our discussions was :
 1. When a Patient is scheduled for an apointment depending on the type of appointment ,the patient is assigned a queue of stages to pass through (procedure)
 2 . The stages are updated by the logged in user (nurse,doctor. e.t.c) if the patients has completed it

**Comment by noxecane** [comment]
After some analysis, I think the appointments module partly solves the problem. A lot of knowledge with regards to the problem was in my head but not properly expressed. 
The ideas is that a user should be able to queue a patient to another user. The only problem with the current appointments module is that there's no `Nursing Station` and `Doctor`.  The queue is the type of appointment. But for the queue to make sense they need to be able to create an appointment without the requirement of specifying an end date. The start data should automatically be the current time. The appointment list should be sorted by the start date too for `first come first serve` experience. If there's anything else I will notify you. With regards to what you designed that's solving a different problem. I'll create an issue for it tomorrow

**Pull request merged**
